#!/usr/bin/env ruby 

class ApplyDeltaCommmand
	
	def ApplyDeltaCommmand.apply_delta(delta_path, contents)
		delta_contents = File.open(delta_path).read
		hunks = delta_contents.split("@@")
		hunks.shift
		half_times = hunks.count/2
		half_times.times do |time|
			header = hunks[time*2]
			contents = hunks[time*2+1]
			puts header
		end
	end

end